/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'leo' at '16-6-29 上午9:47' with Gradle 2.14
 *
 * @author leo, @date 16-6-29 上午9:47
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
